---
- hosts: localhost
  gather_facts: false
  become: true
  tasks:

  - name: Obtain the VLC process
    pids:
      name: vlc
    register: process

  - name: Kill the process if exists
    kill:
      process: "{{ process.pids | join }}"
      signal: SIGKILL
    register: result

  - debug:
      var: result
...
